# Generated by Django 5.2.7 on 2025-11-05 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinicalguideline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disease_name', models.CharField(blank=True, max_length=255, null=True)),
                ('recommended_tests', models.JSONField(blank=True, null=True)),
                ('recommended_treatments', models.JSONField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('country_region', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ClinicalGuideline',
                'db_table_comment': 'Medical guidelines for diseases/conditions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('supabase_user_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
            options={
                'db_table': 'User',
                'db_table_comment': 'Base table for all users (both clinicians and patients)',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnosticinput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'DiagnosticInput',
                'db_table_comment': 'Inputs (images, lab results, notes, genetic) for a diagnostic case',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('dataset_used', models.TextField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('date_trained', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Model',
                'db_table_comment': 'AI/ML models used for diagnosis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis_json', models.JSONField(blank=True, default=dict, null=True)),
                ('generated_by_model', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnosis_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Diagnosis',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_license_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Clinician',
                'db_table_comment': 'Extends user with clinician-specific information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Patient',
                'db_table_comment': 'Extends user with patient-specific information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.diagnosis')),
                ('recommended_text', models.TextField(blank=True, null=True)),
                ('generated_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_reviewed', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'Recommendation',
                'db_table_comment': 'Treatment recommendation based on diagnosis and guidelines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnosticcase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('patient_info_json', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], db_index=True, default='PROCESSING', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'db_table': 'DiagnosticCase',
                'db_table_comment': 'Represents a diagnostic case created by a user',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_set', to='api.diagnosticcase'),
        ),
    ]
