# Generated by Django 5.2.7 on 2025-11-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicalguideline',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='clinician',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='diagnosticinput',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
    ]
